name: ✨ Feature Request
description: 新機能や改善の提案をお聞かせください
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        新機能のご提案をありがとうございます。
        AIエージェントシステムの改善にご協力いただき感謝します。

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能要求の優先度を選択してください
      options:
        - P3 - Low (低)
        - P2 - Medium (中)
        - P1 - High (高)  
        - P0 - Critical (緊急)
      default: 1
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: カテゴリ
      description: 機能要求のカテゴリを選択してください
      options:
        - AIエージェント機能
        - タスク管理機能
        - 通信・コラボレーション機能
        - UI/UX改善
        - パフォーマンス改善
        - セキュリティ機能
        - 監視・分析機能
        - インテグレーション
        - ドキュメント
        - その他
    validations:
      required: true

  - type: dropdown
    id: target_agent
    attributes:
      label: 対象となるAIエージェント
      description: 特定のエージェントに関連する機能の場合は選択してください
      options:
        - CEO
        - CTO
        - Engineering Manager
        - Security Officer
        - QA Lead
        - DevOps Engineer
        - Senior Fullstack Engineer
        - Frontend Specialist
        - Backend Architect
        - Technical Writer
        - Product Manager
        - HR Manager
        - 全エージェント共通
        - 該当なし

  - type: textarea
    id: summary
    attributes:
      label: 機能の概要
      description: 提案する機能について簡潔に説明してください
      placeholder: 何を実現したいか、どのような機能かを一言で表現してください
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解決したい問題
      description: この機能によって解決したい問題や課題を説明してください
      placeholder: |
        現在どのような問題や不便さがありますか？
        なぜこの機能が必要だと思いますか？
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: 問題を解決するための具体的な機能や改善案を詳しく説明してください
      placeholder: |
        どのような機能や改善を提案しますか？
        それはどのように動作するべきですか？
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: ユーザーストーリー
      description: エンドユーザーの視点から、この機能がどのように使われるかを説明してください
      placeholder: |
        「〜として、〜したいので、〜ができるようにしたい」
        
        例：
        - 開発者として、タスクの進捗を一目で把握したいので、ダッシュボードにタスク状況を可視化する機能が欲しい
        - エージェント管理者として、エージェントの負荷を分散したいので、自動的にタスクを再配分する機能が欲しい
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ条件
      description: この機能が完成したと判断するための条件を列挙してください
      placeholder: |
        この機能が実装されたとき、以下のことができるようになる：
        - [ ] 〜ができる
        - [ ] 〜が表示される
        - [ ] 〜の場合に〜が実行される
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる解決策や実装方法があれば説明してください

  - type: textarea
    id: mockups
    attributes:
      label: モックアップ・設計案
      description: UIの改善提案の場合、スケッチやワイヤーフレーム、参考画像があれば添付してください

  - type: dropdown
    id: complexity
    attributes:
      label: 実装の複雑さ（予想）
      description: この機能の実装がどの程度複雑だと思いますか？
      options:
        - 簡単（数時間〜1日）
        - 普通（2-5日）
        - 複雑（1-2週間）
        - 非常に複雑（2週間以上）
        - 分からない

  - type: textarea
    id: impact
    attributes:
      label: 期待される効果・影響
      description: この機能が実装された場合の期待される効果や影響を説明してください
      placeholder: |
        - ユーザビリティの向上
        - 作業効率の改善
        - エラー率の削減
        - パフォーマンスの向上
        - など

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項
      description: 提案前に以下の項目を確認してください
      options:
        - label: 既存のIssueで同様の機能要求がないことを確認しました
          required: true
        - label: この機能が現在のシステムアーキテクチャに適合することを確認しました
          required: false
        - label: この機能要求にビジネス価値があることを確認しました
          required: true